"""Python translation of Polytopia GameLogicAssembly simulation state + board renderer."""

from .board_renderer import BoardRenderer, PIXELS_PER_UNIT, render_game_state
from .example_match import BOARD_PRESETS, build_board_preset, build_example_match, build_four_tribe_board
from .game_state import (
    ActionBase,
    CommandBase,
    CommandTrigger,
    DiplomacyMessage,
    DiplomacyRelation,
    GameSettings,
    GameState,
    GameStateSummary,
    ImprovementState,
    MapData,
    PlayerData,
    PlayerProfileState,
    PlayerState,
    ResourceState,
    TileData,
    UnitState,
    WorldContinent,
    WorldCoordinates,
)
from .map_extensions import to_position, get_depth_for_tile

__all__ = [
    "ActionBase",
    "BoardRenderer",
    "CommandBase",
    "CommandTrigger",
    "DiplomacyMessage",
    "DiplomacyRelation",
    "GameSettings",
    "GameState",
    "GameStateSummary",
    "ImprovementState",
    "MapData",
    "PlayerData",
    "PlayerProfileState",
    "PlayerState",
    "ResourceState",
    "TileData",
    "UnitState",
    "WorldContinent",
    "WorldCoordinates",
    "PIXELS_PER_UNIT",
    "BOARD_PRESETS",
    "build_board_preset",
    "build_example_match",
    "build_four_tribe_board",
    "get_depth_for_tile",
    "render_game_state",
    "to_position",
]
